"""input-remapper integration for host-side arbitrary button binding.

input-remapper stores per-device presets as TOML under
~/.config/input-remapper-2/presets/<device>/<preset>.toml (or the
input-remapper-1 path). This module generates those files.
"""
from __future__ import annotations

import os

PHYSICAL_TO_EVDEV = {
    0: "BTN_LEFT",
    1: "BTN_RIGHT",
    2: "BTN_MIDDLE",
    3: "BTN_SIDE",    # physical Forward
    4: "BTN_EXTRA",   # physical Backward
    5: "BTN_SIDE",    # DPI button, re-exposed as a side button
}


def evdev_button_for(physical_btn_index: int) -> str:
    if physical_btn_index not in PHYSICAL_TO_EVDEV:
        raise ValueError(f"No evdev mapping for physical button index {physical_btn_index}")
    return PHYSICAL_TO_EVDEV[physical_btn_index]


def generate_preset(evdev_button: str, action: str) -> str:
    return (
        "# Generated by hator-config; remove this file to disable.\n"
        f'[[mappings]]\n'
        f'input = "{evdev_button}"\n'
        f'output = "{action}"\n'
    )


def write_preset(device_name: str, evdev_button: str, action: str, preset_dir=None) -> str:
    preset_dir = preset_dir or os.path.expanduser(
        "~/.config/input-remapper-2/presets"
    )
    safe = "".join(c if c.isalnum() or c in " -_" else "_" for c in device_name)
    path = os.path.join(preset_dir, safe, "hator.toml")
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write(generate_preset(evdev_button, action))
    return path
